### PR TITLE
Check for script non-zero exit code

### LINKED ISSUE #35: Track exit code returned by the script
Hi, 

Would you be happy for me to put together a PR to track the exit codes coming back from the scripts?

The use case here is to prevent additional calls to scripts when a failure occurs. Currently I *think* what will happen (based on what I've seen) is that if `read` will exit with non-zero code and not output any `state` (say a network issue has prevented a curl call) the provider does a diff with the current state and observes a change, to rectify this it calls `update`. My expectation would be to have the error cause the `terraform apply` to terminate instead and let the user review the error then re-run as needed. 

This change would mean that scripts should always return a 0 exit code if they want their state output to be persisted or a non-zero code if they want to terminate and display the error. 

An added bonus here is that we'd be able to take the cmd output from the error'd script and return it to Terraform so it'd displayed to the user without setting `TF_LOG=debug` (would only happen when the script error'd but still useful). 

I think I need to change this section:

https://github.com/scottwinkler/terraform-provider-shell/blob/a605c7b5edf970a7428c2f832686355782a7893e/shell/utility.go#L100-L108

To use a pattern like this:

https://stackoverflow.com/a/10385867/3437018

Sound like a useful change?

### PR DESCRIPTION
**Pull request by lawrencegripper**
Fixes #35 

The code will now check that scripts haven't exited with a non-zero code. The error, stdout and stderr will be returned to the user.

image

### CODE REVIEW

**Comment by scottwinkler** [comment]
Thanks for your contribution!

**Comment by lawrencegripper** [comment]
np, thanks for review and merge. Would you be able to cut a release?

**Comment by scottwinkler** [comment]
I'll do it  later today or tomorrow. I want to rewrite the makefile to make it easier to create new releases

**Comment by lawrencegripper** [comment]
Cool, yeah no rush. For another project I use the goreleaser tool to push releases from master build. Might be useful https://goreleaser.com/

**Comment by lawrencegripper** [comment]
Thanks for pushing the release :+1: and thanks again for the hard work on the provider it's super useful.

**Pull request merged**
