### PR TITLE
remove force new

### PR DESCRIPTION
**Pull request by scottwinkler**
removing the need for force new on many attributes. also fixing the way error logging works. closes issues #67. #60, #59

### CODE REVIEW

**Comment by AdamCoulterOz** [comment]
@scottwinkler I've just noticed that this now causes my resources to force replacement whenever the environment variables change. Is this intended? FYI - @pacon-vib

**Comment by scottwinkler** [comment]
My mistake, I'll fix this. You're right it shouldn't be force new because if it changes it is handled by the update function.

**Comment by AdamCoulterOz** [comment]
Thanks so much @scottwinkler ... I'm writing a blog post for my company (servian.com) about terraform 0.13 and using a pattern such as your shell provider (and using it as an example) as a much more logical extension mechanism to wrap existing client cli's rather than having to develop a full golang tool chain to make a tiny change.  Something terraform core should incorporate a first party way to publish full providers.

It will be published here sometime in the next 3-4 weeks: https://medium.com/weareservian

**Comment by jwicks** [comment]
@scottwinkler Are you still planning to add a fix for the issue @AdamCoulterOz mentioned?

**Comment by scottwinkler** [comment]
Sorry I forgot about this. Let me create a new issue to track it. I will get it done in the next few days.

@AdamCoulterOz nice work on the module.

**Pull request merged**
